### ISSUE TITLE
Security: Don't use primary keys in URLs

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#10]
* Makes XSS attacks a little easier
* Displays your volume, which provides criminal attackers a gauge to determine if you are worth attacking

**Comment by natecox** [comment]
Yes, a thousand times yes. I've also taken to using UUIDv4 as primary keys instead of the default auto-increment integer for increased protection.

**Comment by audiolion** [comment]
on the same note I found [this article](https://medium.com/@hakibenita/bullet-proofing-django-models-c080739be4e#.xy7x1u2qj) really informative and would love to see some of its content added to 1.11

**Comment by pydanny** [comment]
:ship:

**Comment by ddahan** [comment]
@natecox Very interesting. Would you do it for every models or just specific ones?
Do you create the uuid field manually for theses models or do you make your class inherit from another?

**Comment by natecox** [comment]
@ddahan I've started using UUIDv4 on every model I do and haven't looked back. Normally I write a mixin for the classes with the id predefined; however, for small projects I may just do it explicitly.

**Comment by ddahan** [comment]
@natecox Ok great! However in development environment, pks are easiers to deal with (for example if you want to get your object in a python shell, with a REST client, etc.). Maybe there is a way to have different kinds of primary keys according to an environment?

**Comment by audiolion** [comment]
@ddahan just let django do its automatic dummy auto increment pk, and then have a uuid field on the model that you use for public facing URLs, api calls, etc.

**Comment by natecox** [comment]
@ddahan I'm not sure I understand your complaint. When you use the `primary_key=True` flag on a model field it _becomes_ the primary key for the model instance. `model_instance.pk` will reference whatever field you have set as the primary key, same with `Model.objects.get(pk=whatever)`

**Comment by ddahan** [comment]
@natecox my mistake I meant "id" not "pk".
However @audiolion is right, I don't need to replace id by uuid, just using both in // allow me to deal with the one I want.

**Comment by bluesurfer** [comment]
But.. What if I want to have a user friendly URL with a short uuid? 

I really would use UUID everywhere as @pydanny suggests but they are way too long: YouTube uses 11 characters to identify a video, Django UUIDField produces 32 characters. Moreover, I don't understand the "displaying your volume problem. Database entries may be deleted, plus I could set an initial start for the primary key.

**Comment by natecox** [comment]
@bluesurfer In general I would say that IDs of any sort are very user **un**friendly. If you want to have a short URL for a model instance, include a slug field and reference that instead of the primary key.

If you use sequential IDs, an attacker gets an immediate sense of the size of your database and makes it very easy to iteratively query every element in the database by running a simple loop. Using a non-sequential PK is one part of a multi-phase protection scheme to help make intruder's lives more difficult.
