### ISSUE TITLE
Flavor model's flavor choices is not correct

### ISSUE THREAD

**Issue by tianhongjie** [twoscoops/two-scoops-of-django-1.11#101]
## Location within the Book

* Chapter or Appendix: chapter_10
* Section: 07
* Subsection:

## Description 

In file chapter_10_example_07.py Line 48 is not correct.

> If grammar, enter problematic text here, otherwise delete this line.

```
If code-related, enter it within these backticks. Otherwise, delete this segment.
```

``` # Wrong
    STATUS_CHOICES=(
        (STATUS_0, 'zero'),
        (STATUS_1 = 'one'),
    )
```

``` # OK
    STATUS_CHOICES=(
        (STATUS_0, 'zero'),
        (STATUS_1, 'one'),
    )
```

**Comment by pydanny** [comment]
Fixed in 235081dfb381c61ab4682b323574677b4c8d848b
