### ISSUE TITLE
Example 7.4 text overflow

### ISSUE THREAD

**Issue by belak** [twoscoops/two-scoops-of-django-1.11#103]
## Location within the Book

* Chapter or Appendix: 7
* Section: 3
* Subsection: Example 7.4

## Description 

Example 7.4 overflows from the box. This is seen in the pdf and print versions.

![example 7.4 overflow](https://user-images.githubusercontent.com/107097/28442096-61dd1a38-6d63-11e7-83a0-a4649218f7f9.png)

In the print version, `Not good` gets cut off midway through the second o as well.

**Comment by belak** [comment]
Ah. I may have just gotten the joke. Anyway, if you do a later printing, the "Not good" should probably be fixed.

**Comment by pydanny** [comment]
Thanks for catching the print issue with `good`. Printing is a subtle, tricky business.
