### ISSUE TITLE
12.8.1 Error in form widgets directory

### ISSUE THREAD

**Issue by ooknosi** [twoscoops/two-scoops-of-django-1.11#106]
## Location within the Book

* Chapter or Appendix: 12 | Form Fundamentals
* Section: 12.8 | Customizing Widgets
* Subsection: 12.8.1 | Overriding the HTML of Built-In Widgets

## Description 

There's an error in the directory for overriding form widgets:

> Once that’s complete, create in your _templates_ directory a directory at _django/forms/templates_ and
start overriding templates.

should read as

> Once that’s complete, create in your _templates_ directory a directory at **_django/forms/widgets_** and
start overriding templates.

**Comment by pydanny** [comment]
🚢 🍨 

Got a real name so we can acknowledge you in the credits?

**Comment by ooknosi** [comment]
@pydanny Sure. I'm going to PM you in Reddit to preserve a modicum of privacy. Thank you!
