### ISSUE TITLE
typo in chapter 7.5 Don’t Drop Down to Raw SQL Until It’s Necessary

### ISSUE THREAD

**Issue by prybicka** [twoscoops/two-scoops-of-django-1.11#107]
## Location within the Book

* Chapter or Appendix: 7 Queries and the Database Layer
* Section: 7.5 Don’t Drop Down to Raw SQL Until It’s Necessary
* Subsection: -

## Description 
First paragraph.

> This does’t just apply to internal project code, but also to the rest of the Django world.

I think that does't should be doesn't.

**Comment by pydanny** [comment]
🚢 🍨 

Got a real name so we can acknowledge you in the credits?

**Comment by prybicka** [comment]
Yes, already available in my profile.

**Comment by pydanny** [comment]
Thanks!
