### ISSUE TITLE
typo in chapter 16.2 Illustrating Design Concepts With a Simple API

### ISSUE THREAD

**Issue by prybicka** [twoscoops/two-scoops-of-django-1.11#108]
## Location within the Book

* Chapter or Appendix: 16 Building REST APIs With Django REST Framework
* Section: 16.2 Illustrating Design Concepts With a Simple API
* Subsection: -

## Description 

>Example 16.6: Taditional REST-style API definition

I think that Taditional should be Traditional.

**Comment by pydanny** [comment]
🚢  🍨
