### ISSUE TITLE
Examples 6.5/6.7 - ImportError

### ISSUE THREAD

**Issue by bogdal** [twoscoops/two-scoops-of-django-1.11#109]
## Location within the Book

* Chapter: 6
* Section: 4
* Subsection: 7 and 8

## Description 
Examples `6.5` and `6.7` contain an incorrect path to the `Django models` module.

There is:
```python
from django import models
```

Should be:
```python
from django.db import models
```

**Comment by pydanny** [comment]
🚢 🍨 

If we do a 2.2 version in a few years, we might need you as a tech reviewer. 👍
