### ISSUE TITLE
Link to article on avoiding GFKs

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#11]
While we give a light explanation, we've wanted to have a deeper explanation of this for years. Fortunately, Luke Plant wrote: http://lukeplant.me.uk/blog/posts/avoid-django-genericforeignkey/

**Comment by natecox** [comment]
It's a good article. I use GFKs occasionally, but I always very carefully evaluate when I'm using them. It's too easy to think of them as a standard convention rather than an exception.

**Comment by pydanny** [comment]
Done! 

🍨
