### ISSUE TITLE
Examples 7.3/7.4/7.5 - django.models.Q ImportError

### ISSUE THREAD

**Issue by bogdal** [twoscoops/two-scoops-of-django-1.11#110]
## Location within the Book

* Chapter: 7
* Section: 3
* Subsection: main and 1

## Description 

Examples `7.3`, `7.4` and `7.5` contain an incorrect path to the `Q` object.

There is:

```python
from django.models import Q
```

Should be:
```python
from django.db.models import Q
```

**Comment by pydanny** [comment]
🚢 🍨
