### ISSUE TITLE
Example 16.5, table 16.3 - incorrect param name

### ISSUE THREAD

**Issue by bogdal** [twoscoops/two-scoops-of-django-1.11#111]
## Location within the Book

* Chapter: 16
* Section: 2

## Description 

In the`example 16.5` and `table 16.3` instead of `slug` we should use `uuid`.

There is:

```python
/flavors/api/:slug/
```

Should be:
```python
/flavors/api/:uuid/
```

**Comment by pydanny** [comment]
🚢  🍨
