### ISSUE TITLE
Grammatical error in 26.10.4

### ISSUE THREAD

**Issue by changeprogramming** [twoscoops/two-scoops-of-django-1.11#113]
## Location within the Book

* Chapter or Appendix: Chapter 26
* Section: 10
* Subsection: 4

## Description 

> First sentence in 3) of ordered list has a grammatical error. "... they gain the ability to not only falsify session data and also execute arbitrary code." I suggest "... they gain the ability to not only falsify session data, but also to execute arbitrary code." or "they gain the ability to falsify session data and execute arbitrary code."

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
