### ISSUE TITLE
Confusion at 24.2.4: Did you mean "ATOMIC_REQUESTS to False"?

### ISSUE THREAD

**Issue by yshean** [twoscoops/two-scoops-of-django-1.11#114]
## Location within the Book

* Chapter: 24
* Section: 2
* Subsection: 4

## Description 

In the subsection title, you wrote "Switch `ATOMIC_REQUESTS` to False". But in the content, you wrote:
> ...if your bottleneck analysis points to transactions causing too much delay, it’s time to change the project run as `ATOMIC_REQUESTS` to True.

So in the case of transactions causing too much delay, do you wish to suggest the user to switch `ATOMIC_REQUESTS` to True or False?

**Comment by tunecrew** [comment]
Just noticed this too - according to the Django docs at [https://docs.djangoproject.com/en/1.11/topics/db/transactions/](https://docs.djangoproject.com/en/1.11/topics/db/transactions/)

"A common way to handle transactions on the web is to wrap each request in a transaction. Set ATOMIC_REQUESTS to True in the configuration of each database for which you want to enable this behavior."

So I think it is a typo in TSD and shoudl read " it’s time to change the project run as ATOMIC_REQUESTS to False"

**Comment by pydanny** [comment]
🤦 

🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
