### ISSUE TITLE
Indentation error in example 12.10

### ISSUE THREAD

**Issue by kamilkijak** [twoscoops/two-scoops-of-django-1.11#118]
## Location within the Book

* Chapter or Appendix: 12
* Section: 8
* Subsection: 2

## Description 
There is a wrong indentation of a comment of `IceCreamFlavorInput` class.
Also, code of that example goes out of bands in my book (paper version), please check the photo below.

<img src="https://user-images.githubusercontent.com/20818418/33798965-c2b57312-dd22-11e7-9a9b-254b49f452d8.jpg" width="500" />

## Fix
Proposed fix in #117

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the 3.x edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
