### ISSUE TITLE
Typo in "code/chapter_05_example_31.py" file

### ISSUE THREAD

**Issue by bloodpet** [twoscoops/two-scoops-of-django-1.11#119]
## Location within the Book

* Chapter 5 (but this issue is related to the file here in github)

## Description 
Original code is:
```
return abspath(join(bas_dir, *dirs))
```
It should be:
```
return abspath(join(base_dir, *dirs))
```

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
