### ISSUE TITLE
Experiment writing TSD LaTeX to Kindle 8 script

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#12]
* Can't use Pandoc, as our flavor of LaTeX is too different. 
* KIndle 8 is too customizable to rely on a generic third-party script or tool

**Comment by pydanny** [comment]
Been using @dabeaz's sly and so far have lexed about 80% of elements. Next up is writing the parser.

**Comment by pydanny** [comment]
97% of the first chapter is now successfully lexed and parsed. Other chapters are breaking the current lexer, but getting them working is just a matter of time. 😄

**Comment by pydanny** [comment]
Not having that much time to work on this is a bummer. We're seeing what we can do with `htlatex` instead.

**Comment by pydanny** [comment]
I think we're going to give up and just use .KPF (textbook) format. That means Amazon-only, and will work on all phones and computers, but not e-ink devices

**Comment by natecox** [comment]
Dang, I just bought a Kindle Voyage.
