### ISSUE TITLE
Spelling mistake of "flavor" in Figure 4.4

### ISSUE THREAD

**Issue by jeffmaher** [twoscoops/two-scoops-of-django-1.11#121]
## Location within the Book

* Chapter or Appendix: 4
* Section: 3
* Subsection: Figure 4.4

## Description 

![image](https://user-images.githubusercontent.com/950486/34308516-cb3b503a-e71b-11e7-806a-84df4d8c4e37.png)

> Figure 4.4: Two small, single-flavor pints are better than a giant, 100-fiavor container.

Small mistake: "flavor" is spelling "fiavor". Found in the Amazon ebook.

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
