### ISSUE TITLE
12.8: Small typos

### ISSUE THREAD

**Issue by jeffmaher** [twoscoops/two-scoops-of-django-1.11#122]
## Location within the Book

* Chapter or Appendix: 12
* Section: 8
* Subsection: N/A

## Description 

> One of our favorite features about Django 1.11 is [how] trivial it is to override ...

![image](https://user-images.githubusercontent.com/950486/34386621-925483a6-eaf7-11e7-9f60-aa3a4e587855.png)

and

> While this example is silly, it illustrates ~~what~~ how to extend an ...

![image](https://user-images.githubusercontent.com/950486/34386809-924f09f2-eaf8-11e7-9e3f-5f0bd8777377.png)

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
