### ISSUE TITLE
Appendix A - django channels wrong link

### ISSUE THREAD

**Issue by denismorozov** [twoscoops/two-scoops-of-django-1.11#123]
## Location within the Book

* Appendix: A
* Section: Asynchronous

## Description

Given the resource description - "Official Django websockets interface, can also be used as task queue" - the link should be https://pypi.python.org/pypi/channels instead of https://pypi.python.org/pypi/django-channels.

Thanks for the great book!

**Comment by natecox** [comment]
Man, that's a bit confusing. Good catch.

**Comment by pydanny** [comment]
🚢 🍨  Look for your name in the book when TSD 3.x is released!
