### ISSUE TITLE
#SUGGESTİON change json example code

### ISSUE THREAD

**Issue by iamnotagentleman** [twoscoops/two-scoops-of-django-1.11#129]
Chapter or Appendix: Chapter 5 Settings And Requirements Files
 Section:  5.4 When You Can't Use Enivorment Variables
 Subsection: 5.4.1 Using Json Files

Firstly sorry for my grammar and word issues my english is not good.  also ı first time opening an issue

my suggestion:

need change json example code. the code using json.loads() function for work with files but json
.loads() not good choice for files. the function usually using for string. instead use json.load() function is working well with json files.

More information : https://docs.python.org/3/library/json.html

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
