### ISSUE TITLE
Discuss Serverless code

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#13]
* AWS Lambda
  * Deployment via Gordon or Apex
  * Zappa
  * Receiving web hooks
  * Sending web hooks
  * The importance of testing

* Other services

**Comment by natecox** [comment]
Zappa looks like a fantastic solution for serverless Django. The biggest question that I have on the topic is how to handle session/state management in a serverless environment.

**Comment by pydanny** [comment]
With Django, session management in production is through use of a datastore such as Redis (our preference), the SQL database, etc. So I don't think session management is a problem.

That said, our current preference is to use Serverless not for hosting of a Django project, but for slow process such as file management, heavy processing, et al. We also use a few tiny flask apps that don't use databases with serverless.

**Comment by natecox** [comment]
That makes sense, seems like a good option for that sort of thing. I've held off on serverless with Django simply because it seems counter-intuitive to spin a whole Django instance up and down repeatedly. Still something I'd like to look into more in the future.

**Comment by pydanny** [comment]
Just covered just Serverless code in the asynchronous task queue chapter. 😄
