### ISSUE TITLE
Clarification about core/urls.py

### ISSUE THREAD

**Issue by simkimsia** [twoscoops/two-scoops-of-django-1.11#136]
## Location within the Book

* Chapter or Appendix: 16
* Section: 16.3.1

## Description 

>We always place routers in urls.py.

Which urls.py you referring to? the urls.py within the api folder or the urls.py within the config folder?

**Comment by pydanny** [comment]
Yes. Put routers in the urls.py at either level. Don't put them in other modules named other things.

🚢 🍨 You'll be given mention in the acknowledgements of the next edition!
