### ISSUE TITLE
BooleanField sets blank=true automatically

### ISSUE THREAD

**Issue by ImplicitCoder** [twoscoops/two-scoops-of-django-1.11#137]
## Location within the Book

* Chapter or Appendix: Chapter 6
* Section: 6.4 Django Model Design
* Subsection: 6.4.4 When to use Null and Blank

## Description 
 In the handy table, it might be interesting to notice that on a BooleanField, `blank=True` is the default. 

This was very confusing for me until I understood about the reasoning about it through StackOverflow:

https://stackoverflow.com/questions/19328302/django-modelform-doesnt-seem-to-validate-booleanfield.

Mentioning this in the table might save others (a lot of) testing time..

**Comment by pydanny** [comment]
New development, but we'll put it into the book.
