### ISSUE TITLE
Wrong name for an assertion method

### ISSUE THREAD

**Issue by brunato** [twoscoops/two-scoops-of-django-1.11#138]
## Location within the Book

* Chapter or Appendix: 22
* Section: 3
* Subsection: 9

## Description 

> Python 2.7: ListItemsEqual() , Python 3+ assertCountEqual()

*ListItemsEqual()* is not an assertion method of Python 2.7, should be *assertItemsEqual()*.

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition to be released on May 11!

https://www.feldroy.com/products/two-scoops-of-django-3-x
