### ISSUE TITLE
URL duplicated before JavaScript Style Guide list in Ch 1 section 1.7.1

### ISSUE THREAD

**Issue by sampart** [twoscoops/two-scoops-of-django-1.11#140]
## Location within the Book

* Chapter or Appendix: 1
* Section: 1.7
* Subsection: 1.7.1

## Description 

Just before the list whose first items begins with "Standard combined JavaScript and Node.js Style Guide", the following text is given on a line on its own (in standard font):
> https://github.com/feross/standard

This URL is then given (in slightly adapted form) at the end of the first bullet point.  I think the instance of it before the list can be removed - it looks like a heading as it has a line to itself, but it isn't.

Really enjoying the book so far, and love how you track issues etc on Github!

**Comment by pydanny** [comment]
🚢 🍨 You'll be given mention in the acknowledgements of the next edition!
