### ISSUE TITLE
Typo in SSL labs link

### ISSUE THREAD

**Issue by jcu721** [twoscoops/two-scoops-of-django-1.11#144]
## Location within the Book

* Chapter or Appendix: 26
* Section: 6
* Subsection: 3

## Description 

"use the Qualys SSL Labs server test at sllabs.com/ssltest/ to see how well you did"

That link takes you to the kinda cool site of Secret Lair labs, link should actually be https://www.ssllabs.com/ssltest/ . 

i.e. sl labs vs ssl labs.

**Comment by pydanny** [comment]
🚢 🍨

**Comment by pydanny** [comment]
🚢 🍨  Look for your name in the book when TSD 3.x is released!
