### ISSUE TITLE
URL namespace requires setting of app_name

### ISSUE THREAD

**Issue by awtimmering** [twoscoops/two-scoops-of-django-1.11#151]
## Location within the Book

* 8.4 Section: Use URL Namespaces

## Description 

[Snippet](https://github.com/twoscoops/two-scoops-of-django-2.0-code-examples/blob/master/code/chapter_08_example_04.py):

```
urlpatterns += [
    path('tastings/', include('tastings.urls', namespace='tastings')),
]
```
yields:

```
django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.
```

Not sure about the best solution, but details [here](https://docs.djangoproject.com/en/2.2/topics/http/urls/#namespaces-and-include).

**Comment by ragnarok22** [comment]
I think this is due to the Django version. In older version of django app_name are not required

**Comment by awtimmering** [comment]
Thank you, makes sense.
