### ISSUE TITLE
Consider adding enums as choice options

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#19]
With the advent of Python 3.5+, this is a viable option. 

References:

* https://docs.python.org/3/library/enum.html
* http://anthonyfox.io/2017/02/choices-for-choices-in-django-charfields/

**Comment by natecox** [comment]
I've been using Enum as a choice mechanic for a while; but honestly, I think out-of-the box the [Choices class from django-model-utils](https://django-model-utils.readthedocs.io/en/latest/utilities.html#choices) is easier to wrap your head around and offers the same basic benefits.

**Comment by pydanny** [comment]
Done. Many thanks @natecox for your help on this one. 😄 

🚢
