### ISSUE TITLE
Expand chapter on django REST API development

### ISSUE THREAD

**Issue by mattjegan** [twoscoops/two-scoops-of-django-1.11#2]
~I propose that a chapter should be included about developing REST APIs with Django.~

I propose that the existing "Building REST APIs" chapter should even more explicitly target [Django REST Framework](http://www.django-rest-framework.org/) (DRF) by @tomchristie. 

My arguments are as follows:
1. REST API development is being used more and more each yeah due to the need for applications to run on different devices or even as a service rather than a traditional web site/app.
2. According to `vanity` (sourcing download statistics from PyPI) Django has at least 23 million downloads total (over all versions) and DRF has over 5 million. This represents a a large upper bound of ~22% of the community interacting with DRF.

Points I feel need focus:
* Performance (particularly for large and numerous POST and PATCH requests, even bulk requests)
* Security

Disclaimer: I have no affiliation with @tomchristie and have no idea whether he would be willing to collaborate on this.

@pydanny's note: Renamed this issue and changed first paragraph to reflect that a chapter on building REST APIs with DRF already exists, but could/should undergo significant revision.

**Comment by natecox** [comment]
I'd suggest including at least a section on GraphQL, which we may well see overtaking standard REST APIs as the status quo in the near future. The benefits are phenomenal.

**Comment by mattjegan** [comment]
@natecox I'd never heard of GraphQL until now, it looks pretty neat 😄  perhaps it would be best as a reference or suggested alternative at the end of the chapter @pydanny ? It seems that `graphene-django`, the django package for working with GraphQL, has only been downloaded about 2000 times.

**Comment by iyn** [comment]
I would also love to read about the API architecture from the code perspective - how to organize multiple views, serializers etc.

**Comment by pydanny** [comment]
So... um... the current edition (1.8) has material on API architecture in the REST API chapters.

Clearly we need to make it more obvious.

**Comment by natecox** [comment]
haha, I definitely just read it as _expanding_ rather than _including_. Good edit, +1.

**Comment by iyn** [comment]
@pydanny I know, I've read it ;). It's quite basic IMO, but upon reflection, maybe the topic is more generic rather than related to the Django itself.

**Comment by pydanny** [comment]
Changes:

* We now officially endorse DRF as the optimal choice.
* The REST chapter now focuses exclusively on DRF. 
* Other chapters use DRF examples explicitly. Good examples of this include the security and consuming REST chapters.

**Comment by syrusakbary** [comment]
An update on the download stats for `graphene`: around 250.000 downloads, and a steady 1.200 daily (growing 20% each 2 months). The package `graphene-django` have about 500 daily downloads. (74.000 total).

The django integration was first part of the main `graphene` package, and then isolated into a new package `graphene-django` some days before @mattjegan's comment (that's why the downloads were relatively small).

-------

Related SQL query in Google's bigquery:
```sql
SELECT
  COUNT(*) as total_downloads
FROM
  TABLE_DATE_RANGE(
    [the-psf:pypi.downloads],
    TIMESTAMP("20160101"),
    CURRENT_TIMESTAMP()
  )
WHERE
  file.project = 'graphene'
```

Yelp, Reddit, Mozilla, Try.com, Dailymotion are some of the companies using it :)

PS: I would love to see a chapter for it in Two scoops of Django... I think people would really like it! (I'm a little biased though :P )
