### ISSUE TITLE
Consider adding ReactJs and the CSRF token

### ISSUE THREAD

**Issue by fodra** [twoscoops/two-scoops-of-django-1.11#20]
## Location within the Book

* Chapter or Appendix: 17 Consuming REST APIs
* Section: 17.6 AJAX and the CSRF token
* Subsection: ReactJS and the CSRF token

## Description 

See title

**Comment by pydanny** [comment]
Because JS is such an ephemeral topic, we'll just link to someone's solution. Or maybe link to DRF's client side library which could be used as the interface between React and Django.

**Comment by pydanny** [comment]
As I htought, DRF's client JS library handles this for you. Reference: http://www.django-rest-framework.org/topics/api-clients/#instantiating-a-client

Since we're officially endorsing DRF in TSD1.11, we'll just instruct people to use this library.

**Comment by fodra** [comment]
Ok, that works. Just thought about this since the last book version had jQUery and AngularJS sections but no ReactJS.

**Comment by pydanny** [comment]
Closing this as it's covered by DRF's client library.
