### ISSUE TITLE
Consider discussing new Template-based widget rendering

### ISSUE THREAD

**Issue by ddahan** [twoscoops/two-scoops-of-django-1.11#21]
With Django 1.11 comes [a new way to use widgets](https://docs.djangoproject.com/en/1.11/releases/1.11/#template-based-widget-rendering).

This should ease things a lot, and could be an opportunity to update the `Templates: Best practices` part of the book :)

**Comment by pydanny** [comment]
Some early thoughts:

* Keep it simple!
* Widgets shouldn't change data during the rendering process
* Put widgets in named files (`widgets.py`, `fields.py`, etc)

Any other thoughts?

**Comment by pydanny** [comment]
:ship:
