### ISSUE TITLE
Consider adding a whole subsection for Docker local environment

### ISSUE THREAD

**Issue by ddahan** [twoscoops/two-scoops-of-django-1.11#22]
## Location within the Book

* Chapter or Appendix: 2.5 Optional: Identical Environments

## Description 

In TSOD 1.8, `Using Isolated Docker Containers` section is marked as experimental and not explained in details. Given than Docker is now more stable and broadly used, we could consider transforming the "tip" to a subsection (like Vagrant), and explaining it with more details.

**Comment by ddahan** [comment]
There is a how-to here: https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/
As I never used Docker myself (but I'd really like to), I have no idea if it's up to date or not.

**Comment by pydanny** [comment]
Geniuses think alike. This entire issue was updated to match your suggestion quite a ways back. 😄
