### ISSUE TITLE
Consider updating PostgreSQL specific model fields with JSONField

### ISSUE THREAD

**Issue by ddahan** [twoscoops/two-scoops-of-django-1.11#23]
Django 1.9 introduced a new PostgreSQL specific field:
https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield

With the rise of nosql databases, the ability to store and query JSON directly from PostgreSQL (in addition of HStore) seems very welcomed to me. It could be explained in order to prevent people from mixing usage of MongoDB and PostgreSQL if they only need the later.

**Comment by pydanny** [comment]
Astonishingly, considering how much we use `JSONField`, this somehow didn't make it in yet! That will be fixed today. 😄

**Comment by pydanny** [comment]
Done!

**Comment by pydanny** [comment]
@ddahan What's your last name so we can provide proper accreditation in the book?

**Comment by ddahan** [comment]
@pydanny David Dahan (david-dahan.com)
Thanks :)
