### ISSUE TITLE
Wrong default project layout (chapter 3)

### ISSUE THREAD

**Issue by josecostamartins** [twoscoops/two-scoops-of-django-1.11#26]
## Location within the Book

* Chapter or Appendix:  chapter 3
* Section: 3.1 Django 1.11's default project layout
* Subsection: example 3.2: Default Project Layout

## Description 
I've just downloaded django 1.11 and ran the startproject and startapp commands; the default project layout is not as depicted in the book...
The migrations folder is inside the my_app folder and only has an __init.py__

Thanks for the awesome work

**Comment by pydanny** [comment]
Thanks for catching this one for us. I ran `tree` again and you were right! Look for your name in the next update of TSD1.11

:ship: 🍨
