### ISSUE TITLE
Variable name typo (invalid reference to bas_dir)

### ISSUE THREAD

**Issue by aperezalbela** [twoscoops/two-scoops-of-django-1.11#27]
## Location within the Book

* Chapter or Appendix: **_Chapter 5: Settings and Requirements Files_**
* Section: _**5.6 Handling File Paths in Settings**_
* Subsection: **_Example 5.31: Using os.path to discover project root_**

## Description 

This line:
```
    return abspath(join(bas_dir, *dirs))
```

in:

```
def root(*dirs):
    base_dir = join(dirname(__file__), '..', '..')
    return abspath(join(bas_dir, *dirs))
```

contains invalid reference (bas_dir) to **base_dir** and should be:

```
def root(*dirs):
    base_dir = join(dirname(__file__), '..', '..')
    return abspath(join(base_dir, *dirs))
```

**Comment by pydanny** [comment]
Nice catch! This will go into the next update!

🚢 🍨
