### ISSUE TITLE
Example 1.7 is shown as "Don't Do This". Intentional?

### ISSUE THREAD

**Issue by mkoistinen** [twoscoops/two-scoops-of-django-1.11#28]
## Location within the Book

Page 8 of "Early release Alpha" version
Specifically, Example 1.7

## Description 

Example 1.7 appears to be the solution for "Don't Do This" Example 1.6, but 1.7 is also displayed in the "Don't Do This" style box. Shouldn't this be in the lighter-colored box?

**Comment by pydanny** [comment]
🚢  Fixed!
