### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#29]
Reader submitted ideas for stickers when the print version comes out:

* Chocolate Chip Query Dough

**Comment by natecox** [comment]
[Subqueries](https://docs.djangoproject.com/en/1.11/ref/models/expressions/#subquery-expressions) and cream

**Comment by mpachas** [comment]
I love how https://www.stickermule.com works, but I'm sure there are plenty of good options.

**Comment by pydanny** [comment]
We use a Los Angeles-based printer as its always a good idea to support local area businesses. 😄
