### ISSUE TITLE
Punctuation out of place

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#30]
## Location within the Book

* Chapter 4: Fundamentals of Django App Design
* Section: Very first paragraph

## Description 

> The first line ends with: understandably confused by Django’s usage of the word **“app.”**
I think it should be: understandably confused by Django’s usage of the word **“app”.**
with the period after the quotation marks

Thanks!

**Comment by pydanny** [comment]
Fixed!

@mpachas, what's your name so we can credit you properly in the acknowledgements section of the book?

**Comment by mpachas** [comment]
@pydanny I'm Miguel Pachas, thanks.

**Comment by pydanny** [comment]
Okay, you're in the acknowledgments. Thanks @mpachas!
