### ISSUE TITLE
Punctuation (again)

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#31]
## Location within the Book

* Chapter 4: Fundamentals of Django App Design
* Section: 4.1.1 A Practical Example of Apps in a Project

## Description 

> The first line ends with: ice cream shop called **“Two Scoops.”**
I think it should be: ice cream shop called **“Two Scoops”.**
with the period after the quotation marks.

This one is like #30, and I have just find that US grammar goes that way, sorry! (British and Spanish usually doesn't)

Thanks!

**Comment by natecox** [comment]
You're correct on both issues. In examples like these, the punctuation should still go outside the quotation even in American English; the punctuation isn't a part of the quoted text.

See: http://www.quickanddirtytips.com/education/grammar/how-to-use-quotation-marks

**Comment by pydanny** [comment]
:ship: Fixed!
