### ISSUE TITLE
Chapter 3: Config folder discrepancy

### ISSUE THREAD

**Issue by easydevmixin** [twoscoops/two-scoops-of-django-1.11#32]
## Location within the Book

This is for the PDF version named "2017-04-18-early-release-alpha.pdf".

* Chapter or Appendix: Chapter 3
* Section: 3.3 Sample Project Layout
* Subsection: N/A

## Description 

The `config` directory appears located  in different places.

On example 3.4 in page 24 it appears so it is located under `icecreamratings_project/config`. Nevertheless on page 26 looks like it should have to be placed under `icecreamratings_project/icecreamratings/config`.

**Comment by pydanny** [comment]
If I'm not mistaken, the `config` directory is in the root in both places. Please reopen if I am incorrect.

**Comment by easydevmixin** [comment]
Hey @pydanny,

Maybe I'm confused, but my understaning (I'm not native English speaker) from paragraph "*Inside the icecreamratings_project/icecreamratings directory, at the <django_project_root>, we place the following  files/directories*" on page 26 is that the `config/` folder should be under `icecreamratings_project/icecreamratings`.

Nevertheless, on page 24, example 3.4 shows the `config/` folder under `icecreamratings_project/`, not `icecreamratings_project/icecreamratings/`.

Maybe I'm not right, and sorry for the hassle if that's the case, but at least it looks confusing to me.

Cheers!

**Comment by ziadrahhal** [comment]
It is confusing. I opened a similar issue without noticing this entry. I think the section requires a bit of attention.

**Comment by jmwoloso** [comment]
see also: #49

**Comment by jmwoloso** [comment]
@easydevmixin
CC: @pydanny @ziadrahhal 
if you use `cookiecutter-django` to create your project template, the end result is that under the `<REPOSITORY_ROOT>` you will find the directories `config/` and `<YOUR_PROJECT_NAME>/`, so I would say the first example on page 24 is the correct structure and the typo is on page 26. 

see output from `tree` package when run from my `<REPOSITORY_ROOT>` directory

```
<REPOSITORY_ROOT>
├── config
│   ├── __init__.py
│   ├── settings
│   │   ├── base.py
│   │   ├── __init__.py
│   │   ├── local.py
│   │   ├── production.py
│   │   └── test.py
│   ├── urls.py
│   └── wsgi.py
...
└── <YOUR_PROJECT_NAME>
    ├── contrib
   ...
    ├── templates
   ...
    └── users
   ...
```

**Comment by pydanny** [comment]
Thanks so much for the excellent feedback on this issue as well as in #49. What we've done to address the issue is to move the table row describing `config/` from table 3.2 to table 3.1. 

When we send out the next update (today or tomorrow), you should see that the problem has been addressed. If that's not the case, just let us know here and we'll work with you to fix it.

Again, thank you everyone for the feedback. We're putting all of you into our acknowledgement section. 😄 

🚢 🍨

**Comment by pydanny** [comment]
@easydevmixin and @ziadrahhal, could you put your real names on github or post them here so we can credit you properly in the book?

**Comment by easydevmixin** [comment]
@pydanny my real name is **Ramon Maria Gallart Escolà**.

Thanks for the acknowledgment. Two scoops of Django has been an invaluable resource for me since you both released it for Django 1.5. I'm glad you find our contributions useful.

Cheers!

**Comment by ziadrahhal** [comment]
@pydanny my name is Ziad Rahhal 

I was stuck on a django problem; I opened google, typed two scoops of django and to my surprise found an entry that 1.11 is there. I didn't hesitate to purchase. 

Thank you.

**Comment by awtimmering** [comment]
Just flagging: I just purchased the 1.11 book and (while awaiting the paper version) I am reading the ebook, which still seems to have the same discrepancy between chapters 3 and 5 on the package name for the settings.
