### ISSUE TITLE
Text Overflow in Table 35.2 (Appendix G)

### ISSUE THREAD

**Issue by dwbond** [twoscoops/two-scoops-of-django-1.11#34]
## Location within the Book

* Chapter or Appendix:
Appendix G: Security Settings Reference: Table 35.2: Security Settings Reference (page 487)

## Description 
the 'DEBUG_PROPOGATE_EXCEPTION' and SECURE_CONTENT_TYPE_NOSNIFF' names overrun into their adjacent columns

![overflow](https://cloud.githubusercontent.com/assets/1747878/25549972/504fde38-2c43-11e7-9daa-a6037c49c6b6.png)

(Also, I'm not sure if these are also bad things, but appendix G's title appears twice, and table 35.2's title is on the subsequent page.)

**Comment by pydanny** [comment]
Thanks @dwbond! Fixed all you found!

🚢 🍨
