### ISSUE TITLE
fun_function statement should be more verbose and clear

### ISSUE THREAD

**Issue by aperezalbela** [twoscoops/two-scoops-of-django-1.11#36]
## Location within the Book

* Chapter or Appendix: **Chapter 7**
* Section: **7.3 Use Lazy Evaluation to Make Queries Legible**
* Subsection(s):
  **- Example 7.3: Illegible Queries**
  **- Example 7.4: Legible Queries**
  **- Example 7.5: Chaining Queries**
  **- Example 7.6: Debugging with Chained Queries**

## Description 

In both examples there's a:
```
def fun_function(**kwargs):
```

While for some people it's obvious that a {'name': 'something'} kwarg is being received through **kwargs, for some others it's unclear where does "name" comes from.

So *fun_function* would be more verbose and clear if it's stated as:

```
def fun_function(name=None):
```

Since there's no kwarg being received and used other than "name".

**Comment by pydanny** [comment]
Much as I love `kwargs`, I see your point. In the context of what we're talking about in this chapter, it's a confusing distraction. Thanks for identifying this issue.

🚢 🍨
