### ISSUE TITLE
Suggest `pyenv` for Python versioning

### ISSUE THREAD

**Issue by tomatohater** [twoscoops/two-scoops-of-django-1.11#37]
## Location within the Book

* Chapter 2:  The Optimal Django Environment Setup
* Section 2.2: Use Pip and Virtualenv

## Description 

> Alongside virtualenv, consider suggesting the use of `pyenv` for creating isolated environments with specific versions of Python (and potentially `pyenv-virtualenv` to combine).

> As you mention in section 2.1, for many developers, it is not immediately obvious how to install a different version of Python than their machine's default. Maintaining multiple versions is even more baffling to some. `pyenv` is a simpler approach if dockerizing is not in one's blood.

**Comment by natecox** [comment]
[Pyenv](https://github.com/pyenv/pyenv) is certainly a cool project. I tend to use [asdf](https://github.com/asdf-vm/asdf) because I manage several different languages and I like having a single tool for it.

**Comment by easydevmixin** [comment]
+1 to that; and on a Mac it's pretty easy to get it installed using [Homebrew](https://brew.sh/).

**Comment by pydanny** [comment]
My experience with `pyenv` was less than flattering. I had collisions between pyenv and my already installed custom versions of Python. 

It would be awkward for us to recommend a tool we do not like to use.
