### ISSUE TITLE
Flavor/Flavors, Objects

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#40]
## Location within the Book

* Chapter or Appendix: 13.3.3 Gotcha 3: Complex Implied Queries in Templates

Bad Example box 13.11 Template Code Generating Extra Queries
Example box 13.12: Data Queried with select_related

## Description 

> In the comment blocks object should be **objects**, the default manager. 

Also, I guess the name of the related field should be 'flavor', it doesn't seem to be more than one per user.

```python
{% comment %}
List generated via User.object.all().select_related('flavors')
{% endcomment %}
<h1>Ice Cream Fans and their favourite flavors.</h1>
<ul>
{% for user in user_list %}
    <li>
        {{ user.name }}:
        {{ user.flavor.title }}
        {{ user.flavor.scoops_remaining }}
    </li>
{% endfor %}
</ul>
```

**Comment by pydanny** [comment]
🚢 🍨
