### ISSUE TITLE
TODO remains in beta copy

### ISSUE THREAD

**Issue by mkoistinen** [twoscoops/two-scoops-of-django-1.11#41]
## Location within the Book
2017-05-02-early-release-beta
Page 251

## Description 

"TODO shorten forbes.com/sites/limyunghui/2012/04/09/ inspiring-insights-by-instagram-ceo-kevin-systrom-the-man-who-built-a-1-billion-s 2/#6e54f70928b8."

**Comment by pydanny** [comment]
Thanks again for the contribution, @mkoistinen!

🚢 🍨
