### ISSUE TITLE
Error in PostGres Fields Table

### ISSUE THREAD

**Issue by bjtallguy** [twoscoops/two-scoops-of-django-1.11#43]
## Location within the Book

* Chapter or Appendix: 6 Model best practices 
* Section: 6.4 Django Model Design
* Subsection: 6.4.9

## Description 

Looks like table cell "JSONField" "Setting blank=True" was copied from above as JSONField has no auto_now_add, or auto_now methods.

**Comment by pydanny** [comment]
Whoops! I blame the opposing political party!

Fixed it and added you to the acknowledgments section.

🚢 🍨
