### ISSUE TITLE
DateTimeField and timezone

### ISSUE THREAD

**Issue by jaimesanz** [twoscoops/two-scoops-of-django-1.11#45]
## Location within the Book

* Chapter or Appendix: 6 Model best practices
* Section: 6.2
* Subsection: 6.2.(new_subsection)

## Description 

I don't think this is mentioned in the book, but I've been struggling with timezones for a while, and I think it would be useful if you could provide some insight about how to handle DateFields and DateTimeFields when `USE_TZ = True`.

The most common problem that I've had to deal with is that some of the DateFields are inputed by the users (and are not tz aware), and others (like timestamps) are created using `auto_add_now`, which creates a timezone-aware datetime. Then, if I compare those dates, it's not immediately obvious why the result is not what I expected.

Writing tests is also needlessly complicated, because sometimes I use timezone.now() when I should've used timezone.datetime.now() for creating dummy data, which results in tests mysteriously failing only at certain hours.

I've also seen [discussions](http://stackoverflow.com/a/1737078/7331040) about whether or not to use `auto_add` and `auto_add_now`, arguing that using `default=timezone.now` or a custome `save` method is the way to go.

btw thanks a lot for all the great tips :)

**Comment by pydanny** [comment]
We're adding more time-related material now. However, not being experts on the topic, we're mostly just linking to the better resources we've found.

> I've also seen discussions about whether or not to use auto_add and auto_add_now, arguing that using default=timezone.now or a custome save method is the way to go.

Those discussions are over four years old. At the end of 2012, for the 1.5 book, we were told by the core team to just use `auto_add` and `auto_add_now`. None of the core team reviewers for the 1.11 edition book told us to change from `auto_add` and `auto_add_now`.
