### ISSUE TITLE
Duplicate paragraph in 14.1 FiltersAreFunctions

### ISSUE THREAD

**Issue by therefromhere** [twoscoops/two-scoops-of-django-1.11#46]
## Location within the Book

* Chapter or Appendix:
14
* Section:
1
* Subsection:

## Description 
This paragraph and the one before it are pretty much duplicates

> In fact, a quick scan of the source code of Django’s default filters at /git.io/vyzxO shows that the slugify() template filter simply calls the django.utils.text.slugify function.

**Comment by pydanny** [comment]
Again, thanks for the catch!

🚢 🍨
