### ISSUE TITLE
Version number mismatched in API shutdown example (16.5.2)

### ISSUE THREAD

**Issue by therefromhere** [twoscoops/two-scoops-of-django-1.11#47]
## Location within the Book

* Chapter or Appendix:
16
* Section:
5
* Subsection:
2

## Description 

Shouldn't the variable and the view be called apiv2 instead of v1?

```
apiv1_gone_msg = """APIv2 was removed...""""

def apiv1_gone(request): return 
   HttpResponseGone (apiv1_gone_msg)
```

**Comment by pydanny** [comment]
Nice catch! Check for your name in the acknowledgements after the next update!

🚢 🍨
