### ISSUE TITLE
Prefix/Suffix

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#50]
## Location within the Book

* Chapter or Appendix: 14 Template Tags and Filters
* Section: 14.3 Naming Your Template Tag Libraries
* Subsection: The Blue TIP Box

## Description 

> "While that’s been fixed, the convention of adding a _tags.py prefix to template tag libraries has remained."

I think it should be "suffix"

**Comment by pydanny** [comment]
Thanks!

🚢 🍨
