### ISSUE TITLE
A couple of typos in a sentence in §8.7

### ISSUE THREAD

**Issue by inglesp** [twoscoops/two-scoops-of-django-1.11#55]
## Location within the Book

* Version: 2017-05-02-early-release-beta.pdf
* Chapter or Appendix: 8
* Section: 7

## Description 

There are a couple of problems with this sentence:

"How long did it take you to spot the different between Bad Example 8.3 and Bad Example 8.4?"

1) It should be "difference".
2) The example numbers are wrong.  (Do you mean 8.11 and 8.12?)

**Comment by pydanny** [comment]
Thanks Peter! How are you doing these days?

:ship: 🍨

**Comment by inglesp** [comment]
Doing very well thanks!

I hope you're both well -- and congratulations on the latest book.

🍾
