### ISSUE TITLE
typo in chapter 7.3.1 Chaining Queries for Legibility: "evalution"

### ISSUE THREAD

**Issue by you-zhou** [twoscoops/two-scoops-of-django-1.11#57]
## 7.3.1 Chaining Queries for Legibility

* Chapter or Appendix: 7 Queries and the Database Layer
* Section: 7.3 Use Lazy Evaluation to Make Queries Legible
* Subsection: 7.3.1 Chaining Queries for Legibility

## Description 
First paragraph: "Instead of using lazy evalution, it’s possible to chain queries thus:"
I think this evalution should be evaluation.

**Comment by pydanny** [comment]
🚢 🍨 

Added your name to the acknowledgements section.
