### ISSUE TITLE
BASE_DIR definition

### ISSUE THREAD

**Issue by rubi0** [twoscoops/two-scoops-of-django-1.11#60]
## BASE_DIR definiton

* Chapter or Appendix: Chapter 5
* Section: 5.6
* Subsection: Exemple 5.30

## Description 

Exemple 5.30 show us the following definition:

```
BASE_DIR = Path(__file__).resolve().parent.parent
```
And you suggest us to use the following folder structure with our django projects:
```
django_project/
       config/
        |___settings/
                 - local.py
                 - prod.py
                - etc..
```
 With this `DIRS` configuration:

```
MEDIA_ROOT = BASE_DIR / 'media'
   STATIC_ROOT = BASE_DIR / 'static_root'
   STATICFILES_DIRS = [BASE_DIR / 'static']
   TEMPLATES = [
       {
           'BACKEND': 'django.template.backends.django.DjangoTemplates',
           'DIRS': [BASE_DIR / 'templates']
}, ]

```
The problem is that using `BASE_DIR = Path(__file__).resolve().parent.parent` we're defining `BASE_DIR` in `django_project/config`. In order to redirect `BASE_DIR` to the right value, I would suggest to change `BASE_DIR = Path(__file__).resolve().parent.parent` to `BASE_DIR = Path(__file__).resolve().parent.parent.parent`.

**Comment by jmwoloso** [comment]
+1 that's what I had to do as well for it to resolve correctly.

**Comment by pydanny** [comment]
🚢 🍨 

@rubi0 If you give me your last name then I'll be able to include you in the acknowledgements section of the book.

**Comment by rubi0** [comment]
Alessandro Rubio Moraes
