### ISSUE TITLE
Wrong Example 30.1 text

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#61]
## Location within the Book

* Chapter or Appendix: Chapter 30: Deployment: Platforms as a Service
* Section: 30.2 Best practices for Deploying to Paas 
* Subsection: Example 30.1: Make le for Multiple Requirement Deployments

## Wrong code in the box:
<a href="https://imgbb.com/"><img src="https://image.ibb.co/fS4Y3F/Captura_de_pantalla_2017_06_05_a_las_18_55_51.png" alt="Captura_de_pantalla_2017_06_05_a_las_18_55_51" border="0"></a><br /><br />

I have never used makefiles but I guess `^^I` should be an `@`

Tested using Preview.app MBP 13 early 15, 10.11.6 El Capitan

**Comment by pydanny** [comment]
:ship: 🍨 

Thanks again @mpachas!
