### ISSUE TITLE
Make the title of the PDF file more explicit

### ISSUE THREAD

**Issue by lmsteffan** [twoscoops/two-scoops-of-django-1.11#63]
## Location within the Book

Title of PDF file

## Description 

_Suggestion_ : Make the title of the PDF file more explicit.

_Why_ ? When I downloaded the file through my order confirmation, it was saved as "2017-06-03-early-release-beta.pdf". For a user, this is not very useful when it comes to finding the file. You could perhaps rename it to something like "2scoops-2017-06-03-early-release-beta.pdf", at least (Explicit being better than implicit :-) ).

Best regards

**Comment by pydanny** [comment]
Excellent point. We'll do this in the next update!
