### ISSUE TITLE
Typo !!!!!1!!

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#65]
## Location within the Book

* Chapter or Appendix: Chapter 18: Tradeoffs of Replacing Core Components
* Section: 18.1  The Temptation to Build FrankenDjango
* Subsection: The first **Not Okay** reason of the first Fad Temptation

## Description There is a solitary 1 among a sea of exclamation marks

 I need it to be web-scale!!!1!

Maybe that was intentional

I've found those people whose first approach to anything new always goes through "let's try with NoSQL". 🤒

**Comment by pydanny** [comment]
It's intentional. But that way of asking things is no longer in style.
