### ISSUE TITLE
Coloring Mistake in Example 3.10

### ISSUE THREAD

**Issue by alqinae** [twoscoops/two-scoops-of-django-1.11#66]
## Location within the Book

* Chapter or Appendix: 3
* Section: 5
* Subsection: 2
* Example: 3.10

## Description 

"description ('A short description of the project.')? A website for rating ice cream flavors and brands."

The **for** is colored as a keyword. I know that this does not affect anything, but I felt that as long as the final version is not released yet, it is a good idea to modify this tiny issue.

**Comment by mpachas** [comment]
same as #61

**Comment by pydanny** [comment]
The LaTeX package we are using to render our code examples is generating this issue. We can't get around it no matter what we do. Therefore, we have the choice of either removing code highlighting entirely from this example or have the **for** statement highlighted. 

What's your preference?

**Comment by pydanny** [comment]
I've decided to keep the error in the book.
