### ISSUE TITLE
Typo: Facebok instead of Facebook

### ISSUE THREAD

**Issue by debaze** [twoscoops/two-scoops-of-django-1.11#68]
## Location within the Book

* 34: Where and how to ask django questions
* Chapter or Appendix:
* 34.4: Insider tip: be active in the community
* 34.4.1: 9 easy ways to participate

## Description 

 7) Meet other fellow djangonauts on Twitter and Facebok

Should be

 7) ... and Facebook

**Comment by pydanny** [comment]
🚢 🍨 
If you put your full name in your github profile or otherwise provide it, we'll include your name in the acknowledgements.

**Comment by debaze** [comment]
Thanks! My full name is Joris Derese

**Comment by pydanny** [comment]
@debaze! Adding you now! 😄

**Comment by debaze** [comment]
Thanks, I'm feeling proud. And - even as a non icecream lover - your book is delicious for me :+1:
