### ISSUE TITLE
Suggestion: add Gitter as a resource

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#70]
## Location within the Book

* Chapter or Appendix: Chapter 21: Django’s Secret Sauce:  Third-Party Packages
* Section: 21.8 Troubleshooting  Third-Party Packages
* Subsection: Last paragraph

## Description 

Maybe it could be useful to add Gitter as a resource for asking for help for 3rd party packages (as I usually do).
Not sure if it could be added somewhere else along the book.

**Comment by sohamnavadiya** [comment]
Yes, this is a nice suggestion

**Comment by pydanny** [comment]
Got a particular channel to recommend?

**Comment by mpachas** [comment]
https://gitter.im/django/django for general help
https://gitter.im/pydanny/cookiecutter-django 
https://gitter.im/tomchristie/django-rest-framework not from official encode repo, but helpful
https://gitter.im/DjangoGirls/tutorial 
It was nice just to try and find help with codingjoe django-s3file / django-stdimage apps.

**Comment by pydanny** [comment]
I think people have left gitter for other better maintained platforms like discourse/discord/etc.
