### ISSUE TITLE
Difficult (perhaps incorrect) sentences in section 8.7

### ISSUE THREAD

**Issue by lmsteffan** [twoscoops/two-scoops-of-django-1.11#72]
## Location within the Book

* Chapter or Appendix: 8
* Section: 7
* Subsection:

## Description 

I find the following sentences difficult to understand. I think they are not grammatically correct. (OTOH I'm not a native English speaker, so they *might* be grammatical and just difficult to parse).

> However, as we’ve gone from an explicit design to implicit anti-pattern has made this simple view
annoying to maintain. Specifically that we don’t know what the view is supposed to return.

**Comment by pydanny** [comment]
Nice catch!

🍨 🚢 

If you provide your full name we'll add it to the book's acknowledgments section.

**Comment by lmsteffan** [comment]
@pydanny than you. My full name is Laurent Steffan.

**Comment by pydanny** [comment]
@lmsteffan Adding you now! Grats! 😄
