### ISSUE TITLE
epub version?

### ISSUE THREAD

**Issue by brylie** [twoscoops/two-scoops-of-django-1.11#74]
## Description 
It is nice to read ebooks in epub format. For example, epub allows me to increse font size for readability on mobile screen, rather than straining to read tiny PDF text.

What are some considerations regarding offering this ebook in epub format?

**Comment by pydanny** [comment]
We discuss the issue withy e-reader formats briefly at https://www.twoscoopspress.com/pages/two-scoops-of-django-1-11-faq#what-formats

Our considerations:

* In the past, Kindle and epub sales have been a tiny fraction of what our print and PDF orders have been
* The TSD customized LaTeX setup breaks standard conversion tools like Pandoc. We have tried writing a parser from scratch, but this is a huge effort for something that simply doesn't pay us.
* Getting kindle and epub formats to look good across all formats with a textbook is astonishingly hard. It will take weeks of fulltime work on our part to make it meet our exacting specifications. For example, EVERY code sample has to be reset to 39 characters so we don't get bad reviews for having broken code examples. And I can tell you from experience, a single bad review on this issue clobbers online sales.
* That sales for these formats are so small and takes so much time away from our regular consulting work makes it not financially responsible for us to pursue kindle and epub sales. We simply can't afford to do it.

All this said, we're considering publishing it as a textbook on Amazon in July or August. Then, the conversion process is simple. The downside is that it becomes an **Amazon-only** format.

**Comment by brylie** [comment]
I understand that there seems to be significant work involved, with little perceived value. What about publishing the book with a publisher such as [No Starch Press](https://www.nostarch.com/) or [O'Reilly](https://www.oreilly.com/)? They offer epub as an option for all books, so would likely have the tooling available already.

Publishing on No Starch Press or O'Reilly would also avoid pressure to add DRM to the book:
  - [Accepting Amazon's DRM Makes It Impossible To Challenge Its Monopoly](https://www.techdirt.com/articles/20140527/11461627373/accepting-amazons-drm-makes-it-impossible-to-challenge-its-monopoly.shtml)
  - [Doctorow's Law: Who Benefits from DRM?](https://www.eff.org/deeplinks/2009/04/doctorows-law)

All in all, this is a great book and I am still able to read it from my phone. :smile:

**Comment by pydanny** [comment]
We've had extensive discussions with these publishers and others. They do not have any such tooling for converting heavily customized LaTeX into epub. The same goes for converting pdf to epub. It just doesn't exist.

Of course, things may have changed in the past three months. In which case, we're open to working with them.

**Comment by brylie** [comment]
By the way, does TSD export well to HTML?

**Comment by pydanny** [comment]
No. If it did, epub would be easy to implement

**Comment by pydanny** [comment]
We've released DRM-free Kindle and ePub versions on both Two Scoops Press and Amazon. 

https://www.twoscoopspress.com/blogs/news/kindle-and-epub-now-available-for-two-scoops-of-django-1-11

📖  📚  🍨  🍦  😄
