### ISSUE TITLE
Should we release an Amazon-only ebook?

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#75]
For various reasons described in #74, we probably aren't doing an epub or mobi version of the book. It's too much work that won't pay for the time and effort spent.

However, we're considering publishing TSD as a textbook ebook on Amazon in July or August. Then, the conversion process is simple. The downside is that it becomes an Amazon-only format. It won't work on e-ink devices and it won't be available to epub users. Also, because of Amazon's restrictions, we won't be able to sell it from [twoscoopspress.com](https://www.twoscoopspress.com/products/two-scoops-of-django-1-11).

The advantage for us are:

* Super easy conversion from PDF to Kindle textbook format. Generating it is just clicking a button, whereas epub/mobi involves weeks of conversion effort.
* New sales channel!

Potential disadvantages:

* epub users might be upset that we're excluding them
* users of Amazon e-ink readers can't read it (but they can use their phones or tablets)
* Some people won't understand why we can't bundle it with our PDFs (breaks Amazon's terms of service)
* Probably won't make that much money for us

What are your thoughts?

**Comment by giantryansaul** [comment]
> Probably won't make that much money for us

Seems like this is the most important, plus there's a lot of cons that outweigh the pros. I personally wouldn't be interested because of lack of e-ink reader.

**Comment by fjsj** [comment]
If it's super easy to convert and publish, yes.
If not, no. I'm also not interested because of lack of e-ink support.

**Comment by tobyontour** [comment]
If you don't make any money from it then I'd not bother unless you are feeling guilty from the millions you make from the paperback.

**Comment by pydanny** [comment]
> unless you are feeling guilty from the millions you make from the paperback.

I wish we made millions off the paperback. Then we would quit writing code for others and live on a beach for the rest of our lives. Instead, we live in a cheap house in a cheap neighborhood and work on 6.5 year old laptops. :Sad:

**Comment by diek** [comment]
Giving up selling from two scoops press, is that something you will be happy with?

**Comment by pydanny** [comment]
> Giving up selling from two scoops press, is that something you will be happy with?

We can still sell from Two Scoops Press, just not the Amazon-edition version of things.

**Comment by natecox** [comment]
I don't think it's worth it. If TwoScoops were going to look at alternative publishers I'd be much happier with [pragprog](https://pragprog.com/) or [leanpub](https://leanpub.com/), but I'm not convinced the advantages are really there to go out of the way for it.

If we could make it render on my new Kindle Voyage e-ink reader then I'd probably change my mind, but failing that I'd vote no.

**Comment by lmsteffan** [comment]
Another potential disadvantage : sales through Amazon might actually decrease your net benefit if your margin on this new channel is less than on direct sales through your site (I assume that Amazon gets some percentage on "their" sales).
As for myself, I am not interested in buying Amazon-only books (closed format ? not even working on e-ink readers ? forget it) . I would definitely buy an ePub version, but I know that two things do not (yet) go too well with that format: maths, and... code. So I can understand your unwillingness to compromise the quality of your book. (Still, I would buy an ePub version, lower quality notwithstanding).

**Comment by pydanny** [comment]
We've released DRM-free Kindle and ePub versions on both Two Scoops Press and Amazon. 

https://www.twoscoopspress.com/blogs/news/kindle-and-epub-now-available-for-two-scoops-of-django-1-11

📖  📚  🍨  🍦  😄
