### ISSUE TITLE
Typo in the word overwrite

### ISSUE THREAD

**Issue by alqinae** [twoscoops/two-scoops-of-django-1.11#76]
## Location within the Book

* Chapter or Appendix: 3
* Section: 6
* Subsection: 2
* Box: WARNING: Watch Out for Custom Save and Delete Methods

## Description 

> If you **overwrite** a model’s save and delete methods.

I think the correct word is **override**, correct me if I am wrong.

**Comment by pydanny** [comment]
:ship: 🍨 

Your name is going in the acknowledgements!
