### ISSUE TITLE
an HTML vs. a HTML

### ISSUE THREAD

**Issue by alqinae** [twoscoops/two-scoops-of-django-1.11#77]
## Location within the Book

* Chapter or Appendix: 10
* Section: 5
* Subsection: 2
* Paragraph: 2
* Line: 1
* Sentence: 2

## Description 

> This involves creating **a HTML** form that doesn’t modify any  flavor data.

I googled about whether to say **an HTML** or **a HTML**. People are arguing about it. What I found out is it depends on how you pronounce it, if you will read it as **HyperText Markup Language**, then you have to write **a HTML**. In the other hand, if you read it as **H-T-M-L**, then you have to write **an HTML**. In my opinion, nobody will read it as the long form, everybody is saying **an HTML**. Also, in section 8.4 before Example 8.6, you wrote it as **an HTML**.

**Comment by natecox** [comment]
"an" would be the common parlance.

**Comment by pydanny** [comment]
🚢  🍨
