### ISSUE TITLE
References to Bad Example 21.2, Example 21.3

### ISSUE THREAD

**Issue by xusy2k** [twoscoops/two-scoops-of-django-1.11#78]
## Location within the Book

* Version: tsd-1.11-20170609-beta.pdf
* Chapter or Appendix: 21
* Section: 10
* Subsection: 10

## Description 

> What would happen if Bad Example 21.2 were installed to a project with Example 21.3 requirements

I guess it must be "What would happen if Bad Example 21.**3** were installed to a project with Example 21.**4** requirements"

Also I've noticed same code examples at version 2017-06-03-early-release-beta.pdf are much more highlighted following rules dark grey background color instead of light grey because it's a requirements file and there is no syntax highlight

**Comment by pydanny** [comment]
🚢  🍨 

Your name is going into the acknowledgements!

The code highlighting is being adjusted too.
