### ISSUE TITLE
Conventions Used in This Book

### ISSUE THREAD

**Issue by xusy2k** [twoscoops/two-scoops-of-django-1.11#79]
## Location within the Book

* Version: tsd-1.11-20170609-beta.pdf
* Chapter or Appendix: 8
* Section: 4
* Subsection: 2

## Description 

Visually, if I read a gray bordered box I think it's a valid block and if I read a black bordered box I put special attention because I assume it's a "Don't Do This!". I really agree on different colors for differents things.

Following this convention I don't know if it is a bug or a Work In Progress (I've also found #66), but I see Example 8.7 as valid box, but Example 8.8 as invalid.

The same thing happens to me when I read a black border box with a command to execute (see Examples 2.1 and 2.2 at Chapter 2, Section 2, Subsection 1) or with generic information (see Example 3.2 at Chapter 3, Section 1). Is it possible to use the same color criteria also for these boxes?

**Comment by pydanny** [comment]
We're adjusting the colors to increase contrast.
