### ISSUE TITLE
Ungrammatical sentence

### ISSUE THREAD

**Issue by lmsteffan** [twoscoops/two-scoops-of-django-1.11#82]
## Location within the Book

* Chapter or Appendix: 10
* Section: 4
* Subsection: 1

## Description 

> _While_ the Django CBV documentation gives a helpful working example [...] , _but_ this ex-
ample violates the rule
The "while" makes the first clause subordinate to the second one,  while "but" as a conjunction links two independent clauses.

**Comment by natecox** [comment]
Maybe
> The Django CBV documentation gives a helpful working example [...] ;  however, this ex-
ample violates the rule...

**Comment by pydanny** [comment]
:ship: 🍨
