### ISSUE TITLE
Funny-looking end-of-paragraph

### ISSUE THREAD

**Issue by lmsteffan** [twoscoops/two-scoops-of-django-1.11#83]
## Location within the Book

* Chapter or Appendix: 12
* Section: 4
* Subsection: none

## Description 

On first reading, I didn't understand the clause "Now the view" - I went on reading past the example, expecting en ending, something like "is much better". Then, I realized that it mirrors the earlier "First, the form". Perhaps you could say "First, here is the form" and "Then, here is the view" to avoid a mis-reading. (or "now", but I thing "then" is more symmetric with "first").

**Comment by pydanny** [comment]
:ship: 🍨
