### ISSUE TITLE
Typo: seperator

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#88]
## Location within the Book

* Chapter or Appendix: Chapter 29: What About  those Random Utilities?
* Section: 29.3.10 Slugification and Languages Besides English
* Subsection: PACKAGE TIP: awesome-slugify

## Description: 
The first bullet says "Customizing of seperators" -> **separators**

Thanks!!

**Comment by pydanny** [comment]
🚢 🍨
