### ISSUE TITLE
Link text is too long: out of bounds

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#89]
## Location within the Book

* Chapter or Appendix: Chapter 29: What About  those Random Utilities?
* Section: 29.3.10 Slugification and Languages Besides English
* Subsection: PACKAGE TIP: awesome-slugify

## Description: 
The last bullet is a reference at pydanny.com which is too long, maybe it could be forced to be in two lines somehow.

Thanks!!

**Comment by pydanny** [comment]
🚢 🍨
