### ISSUE TITLE
Typo: double ":" punctuation mark

### ISSUE THREAD

**Issue by mpachas** [twoscoops/two-scoops-of-django-1.11#90]
## Location within the Book

* Chapter or Appendix: Chapter 29: What About those Random Utilities?
* Section: 29.4 Exceptions
* Subsection: 29.4.1 django.core.exceptions.ImproperlyConfigured

## Description: 
The last sentence says: "We discuss it in both Chapter 5: Settings and Requirements Files and Appendix E: : Settings Alternatives.", there is a repeated colon after Appendix E:

Thanks!!

**Comment by pydanny** [comment]
🚢 🍨
