### ISSUE TITLE
Incomplete sentence

### ISSUE THREAD

**Issue by lmsteffan** [twoscoops/two-scoops-of-django-1.11#95]
## Location within the Book

* Chapter or Appendix: 35
* Section:
* Subsection: 

## Description 

The very first "sentence" of the chapter actually consists of one subordinate clause without a main clause.
> While we’ve covered a lot of ground here in this fourth edition of the book.

**Comment by natecox** [comment]
Perhaps:

> While we’ve covered a lot of ground here, in this fourth edition of the book, this is just the tip of the ice cream cone. For instance, we plan to write more technical books and grow our open source projects.

**Comment by pydanny** [comment]
:ship:, specifically @natecox's suggestion to @lmsteffan's issue. 👍
