### ISSUE TITLE
Text Overflow on Table 6.2

### ISSUE THREAD

**Issue by louiepascual** [twoscoops/two-scoops-of-django-1.11#97]
## Location within the Book

* Chapter or Appendix: 6
* Section: 4
* Subsection: 4

## Description 
The text "CommaSeparatedInteger-Field" of the first column overflows to the second column.

![overflow](https://user-images.githubusercontent.com/7385258/27593538-fe91fee8-5b89-11e7-8ad6-4f4fcbba00a1.png)

**Comment by pydanny** [comment]
Nice catch @louiepascual! Your name is going into the acknowledgments section of the book!

🚢

**Comment by belak** [comment]
Unfortunately, looks like this made it into the printed copy. :/
