### ISSUE TITLE
Minor inconsistency in URL mention

### ISSUE THREAD

**Issue by thijsvandien** [twoscoops/two-scoops-of-django-1.11#99]
## Location within the Book

* Chapter or Appendix: Acknowledgements
* Section: Technical Reviewers
* Subsection: Ola Sendecka

## Description 

>  Together with her friend Ola Sitarska, she co-founded Django Girls djangogirls.org and she is now a part of Django Girls Foundation.

In most other places, either just the URL is mentioned, or if the name of the organization is also provided, the URL is put in brackets. Perhaps it should also be _the_ Django Girls Foundation, for which I'm not opening a separate issue, since I'm not sure.

**Comment by pydanny** [comment]
This was done per the reviewer's specifications.
